# Sops configuration for per-host secrets
# Each host's secrets file is encrypted with:
#   1. An admin key (for editing secrets on your workstation)
#   2. The host's age key (derived from SSH host key)

keys:
  # Admin key for editing secrets (your workstation)
  # Generate with: age-keygen -o ~/.config/sops/age/keys.txt
  - &admin age1fxxpzpp008n9etmd4eqsk8258h4x934krdenzcjaqss3wec0ccas8fdfe2

  # Per-host keys derived from SSH host keys
  # Get with: ssh-keyscan hostname | ssh-to-age
  # Or on host: cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age
  - &nixnas age1rklrqrtlzxmt0j80v6jn9d30jzas0332j8qtz4mq3nxtzjgtee7sheqg7f 

creation_rules:
  # nixnas secrets - encrypted to admin + nixnas
  - path_regex: secrets/nixnas\.yaml$
    key_groups:
      - age:
          - *admin
          - *nixnas

  # hostB secrets - encrypted to admin + hostB
  # - path_regex: secrets/hostB\.yaml$
  #   key_groups:
  #     - age:
  #         - *admin
  #         - *hostB

  # Shared secrets (if needed) - encrypted to admin + all hosts
  # - path_regex: secrets/shared\.yaml$
  #   key_groups:
  #     - age:
  #         - *admin
  #         - *hostA
  #         - *hostB
